import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{" "}
    //       <code className={styles.code}>pages/index.tsx</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{" "}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
    <h1 className="text-3xl font-bold text-center my-20">
      This is from Home Page to check Next.tsx :){" "}
    </h1>
    // <div>
    //   <div className="flex justify-between items-center text-[#CBD5F6] p-20">
    //     <div className="">
    //       <div>
    //         <h1 className="text-7xl font-bold font-mono text-[#CBD5F6] amiri">
    //           {" "}
    //           Hello!{" "}
    //         </h1>
    //         <h1 className="text-5xl font-bold font-mono text-[#CBD5F6] amiri">
    //           {" "}
    //           This is Emrul Kayes{" "}
    //         </h1>
    //         {/* <span> H </span> */}
    //         {/* <p className="pt-3 text-xl font-semibold text-sky-400 ">
    //           <Typical
    //             steps={["Web Developer", 3500, "MERN Stack Developer", 3500]}
    //             loop={Infinity}
    //             wrapper="p"
    //           />{" "}
    //         </p> */}
    //         {/* <p className='text-lg'> kayes.ek8@gmail.com </p> */}
    //         <p className="py-5 text-[#8892B0]">
    //           {" "}
    //           I am a web developer. In the last few months I have completed more
    //           than 10+ websites project.
    //           <p>
    //             {" "}
    //             I'm expert in HTML, CSS and JavaScript. As a library component
    //             I'm expert in both Bootstrap and TailwindCSS.{" "}
    //           </p>
    //           Also expert in React js as a JavaScript framework. As a backend
    //           good at Node.js and Express.js. Also have good knowledge at
    //           Mongodb database{" "}
    //         </p>

    //         <a
    //           href="resume.pdf"
    //           className="btn border-2 text-[#4AB9A7] font-semibold border-sky-300 normal-case hover:text-black hover:bg-sky-100"
    //           download
    //         >
    //           {" "}
    //           <i>
    //             Download Resume
    //           </i> <i class="fa-solid fa-download pl-2"></i>{" "}
    //         </a>
    //       </div>
    //     </div>
    //     <img
    //       className="w-1/4 rounded-3xl"
    //       src="https://i.ibb.co/7GsGMZ9/1640680010421-1.jpg"
    //       alt=""
    //     />
    //   </div>
    // </div>
  );
};

export default Home;
